# Generated by Django 5.0.6 on 2024-06-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OfficialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('coin', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('price_change', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('market_cap', models.BigIntegerField(null=True)),
                ('market_cap_rank', models.IntegerField(null=True)),
                ('volume', models.BigIntegerField(null=True)),
                ('volume_rank', models.IntegerField(null=True)),
                ('volume_change', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('circulating_supply', models.BigIntegerField(null=True)),
                ('total_supply', models.BigIntegerField(null=True)),
                ('diluted_market_cap', models.BigIntegerField(null=True)),
                ('contracts', models.ManyToManyField(to='coins.contract')),
                ('official_links', models.ManyToManyField(to='coins.officiallink')),
                ('socials', models.ManyToManyField(to='coins.social')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapingJob',
            fields=[
                ('job_id', models.UUIDField(primary_key=True, serialize=False)),
                ('tasks', models.ManyToManyField(to='coins.task')),
            ],
        ),
    ]
